-- ACTIVIDAD 6
DROP DATABASE practica_1_G16;
SHOW DATABASES; 

CREATE DATABASE practica_1_G16;
-- Actividad 6 Full BackUp 1
-- mysql -u root -pDaniel123 practica_1_G16 < /home/danimo/Documents/BasesII/PracticaI/Full_BackUp/Full_BackUp_Act1.sql

USE practica_1_G16;
-- ACTIVIDAD 6 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION;

-- ACTIVIDAD 6 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;

-- ACTIVIDAD 7
DELETE FROM LOG_ACTIVIDAD;
DELETE FROM LOG_HABITACION;
DELETE FROM PACIENTE;
DELETE FROM HABITACION;

-- Actividad 7 Full BackUp 2
-- mysql -u root -pDaniel123 practica_1_G16 < /home/danimo/Documents/BasesII/PracticaI/Full_BackUp/Full_BackUp_Act2.sql

-- ACTIVIDAD 7 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION;

-- ACTIVIDAD 7 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;

-- ACTIVIDAD 8
DROP TABLE LOG_ACTIVIDAD;
DROP TABLE LOG_HABITACION;
DROP TABLE PACIENTE;
DROP TABLE HABITACION;

-- Actividad 8 Full BackUp 3
-- mysql -u root -pDaniel123 practica_1_G16 < /home/danimo/Documents/BasesII/PracticaI/Full_BackUp/Full_BackUp_Act3.sql

-- ACTIVIDAD 8 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION;

-- ACTIVIDAD 8 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;

-- ACTIVIDAD 9
DROP TABLE LOG_ACTIVIDAD;
DROP TABLE LOG_HABITACION;
DROP TABLE PACIENTE;
DROP TABLE HABITACION;

-- Actividad 9 Full BackUp 4
-- mysql -u root -pDaniel123 practica_1_G16 < /home/danimo/Documents/BasesII/PracticaI/Full_BackUp/Full_BackUp_Act4.sql

-- ACTIVIDAD 9 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION;

-- ACTIVIDAD 9 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;

-- ACTIVIDAD 10
DROP TABLE LOG_ACTIVIDAD;
DROP TABLE LOG_HABITACION;
DROP TABLE PACIENTE;
DROP TABLE HABITACION;

-- Actividad 10 Full BackUp 5
-- mysql -u root -pDaniel123 practica_1_G16 < /home/danimo/Documents/BasesII/PracticaI/Full_BackUp/Full_BackUp_Act5.sql

-- ACTIVIDAD 10 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION;

-- ACTIVIDAD 10 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;