USE practica_1_G16;
-- ACTIVIDAD 1 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION;

-- ACTIVIDAD 1 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;

-- ACTIVIDAD 1 BACKUP COMPLETO
-- mysqldump -u root -pDaniel123 practica_1_G16 > /home/danimo/Documents/BasesII/PracticaI/Full_BackUp/Full_BackUp_Act1.sql

-- ACTIVIDAD 1 BACKUP INCREMENTAL
-- mysqldump -u root -pDaniel123 practica_1_G16 HABITACION > /home/danimo/Documents/BasesII/PracticaI/BackUp_Incremental/Incremental_Backup_Act1.sql

-- ACTIVIDAD 2 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION;

-- ACTIVIDAD 2 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;

-- ACTIVIDAD 2 BACKUP COMPLETO
-- mysqldump -u root -pDaniel123 practica_1_G16 > /home/danimo/Documents/BasesII/PracticaI/Full_BackUp/Full_BackUp_Act2.sql

-- ACTIVIDAD 2 BACKUP INCREMENTAL
-- mysqldump -u root -pDaniel123 practica_1_G16 PACIENTE > /home/danimo/Documents/BasesII/PracticaI/BackUp_Incremental/Incremental_Backup_Act2.sql


-- ACTIVIDAD 3 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION;

-- ACTIVIDAD 3 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;

-- ACTIVIDAD 3 BACKUP COMPLETO
-- mysqldump -u root -pDaniel123 practica_1_G16 > /home/danimo/Documents/BasesII/PracticaI/Full_BackUp/Full_BackUp_Act3.sql

-- ACTIVIDAD 3 BACKUP INCREMENTAL
-- mysqldump -u root -pDaniel123 practica_1_G16 LOG_ACTIVIDAD > /home/danimo/Documents/BasesII/PracticaI/BackUp_Incremental/Incremental_Backup_Act3.sql

-- ARREGLO 
ALTER TABLE LOG_ACTIVIDAD CHANGE timestampx timestamp VARCHAR(100);
ALTER TABLE LOG_HABITACION CHANGE timestampx timestamp VARCHAR(100);
ALTER TABLE LOG_HABITACION CHANGE statusx status VARCHAR(45);

-- ACTIVIDAD 4 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION;

-- ACTIVIDAD 4 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;

-- ACTIVIDAD 4 BACKUP COMPLETO
-- mysqldump -u root -pDaniel123 practica_1_G16 > /home/danimo/Documents/BasesII/PracticaI/Full_BackUp/Full_BackUp_Act4.sql

-- ACTIVIDAD 4 BACKUP INCREMENTAL
-- mysqldump -u root -pDaniel123 practica_1_G16 LOG_ACTIVIDAD > /home/danimo/Documents/BasesII/PracticaI/BackUp_Incremental/Incremental_Backup_Act4.sql

-- ACTIVIDAD 5 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION;

-- ACTIVIDAD 5 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;

-- ACTIVIDAD 5 BACKUP COMPLETO
-- mysqldump -u root -pDaniel123 practica_1_G16 > /home/danimo/Documents/BasesII/PracticaI/Full_BackUp/Full_BackUp_Act5.sql

-- ACTIVIDAD 5 BACKUP INCREMENTAL
-- mysqldump -u root -pDaniel123 practica_1_G16 LOG_HABITACION > /home/danimo/Documents/BasesII/PracticaI/BackUp_Incremental/Incremental_Backup_Act5.sql