USE practica_1_G16;

-- ACTIVIDAD 11 Eliminacion de Datos
DROP TABLE LOG_ACTIVIDAD;
DROP TABLE LOG_HABITACION;
DROP TABLE PACIENTE;
DROP TABLE HABITACION;

-- ACTIVIDAD 11 Restauracion Backup Incremental 1
-- mysql -u root -pDaniel123 practica_1_G16 < /home/danimo/Documents/BasesII/PracticaI/BackUp_Incremental/Incremental_Backup_Act1.sql

-- ACTIVIDAD 11 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SHOW TABLES; 

-- ACTIVIDAD 11 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SHOW TABLES;

-- ACTIVIDAD 12 Restauracion Backup Incremental 2
-- mysql -u root -pDaniel123 practica_1_G16 < /home/danimo/Documents/BasesII/PracticaI/BackUp_Incremental/Incremental_Backup_Act2.sql

-- ACTIVIDAD 12 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SHOW TABLES; 

-- ACTIVIDAD 12 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE ;
SHOW TABLES;

-- ACTIVIDAD 13 Restauracion Backup Incremental 3
-- mysql -u root -pDaniel123 practica_1_G16 < /home/danimo/Documents/BasesII/PracticaI/BackUp_Incremental/Incremental_Backup_Act3.sql

-- ACTIVIDAD 13 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SHOW TABLES; 

-- ACTIVIDAD 13 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE ;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SHOW TABLES;


-- ACTIVIDAD 14 Restauracion Backup Incremental 4
-- mysql -u root -pDaniel123 practica_1_G16 < /home/danimo/Documents/BasesII/PracticaI/BackUp_Incremental/Incremental_Backup_Act4.sql

-- ACTIVIDAD 14 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SHOW TABLES; 

-- ACTIVIDAD 14 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE ;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SHOW TABLES;

-- ACTIVIDAD 15 Restauracion Backup Incremental 5
-- mysql -u root -pDaniel123 practica_1_G16 < /home/danimo/Documents/BasesII/PracticaI/BackUp_Incremental/Incremental_Backup_Act5.sql

-- ACTIVIDAD 15 (SELECT DE TABLAS)
SELECT * FROM HABITACION;
SELECT * FROM PACIENTE;
SELECT * FROM LOG_ACTIVIDAD;
SELECT * FROM LOG_HABITACION; 

-- ACTIVIDAD 15 (SELECT COUNT DE TABLAS)
SELECT COUNT(*) AS HABITACION FROM HABITACION ;
SELECT COUNT(*) AS PACIENTE FROM PACIENTE ;
SELECT COUNT(*) AS LOG_ACTIVIDAD FROM LOG_ACTIVIDAD;
SELECT COUNT(*) AS LOG_HABITACION FROM LOG_HABITACION;

